### ISSUE TITLE
remove all empty lines

### ISSUE THREAD

**Issue by izzetseydaoglu** [usernamehw/vscode-remove-empty-lines#10]
when i set remove-empty-lines.allowedNumberOfEmptyLines=1, remove all lines

**Comment by usernamehw** [comment]
Is this a bug or a feature request?. I don't understand what is stated here.

**Comment by izzetseydaoglu** [comment]
Hello, thank you for your feedback.
I use GoogleTranslate now because my English language is not good enough.

to file "settings.json" remove-empty-lines.allowedNumberOfEmptyLines=2; I defined the setting. But it still deletes all spaces. I want it to accept at least 2 spaces.

**Comment by izzetseydaoglu** [comment]
> Is this a bug or a feature request?. I don't understand what is stated here.

Hello, thank you for your feedback.
I use GoogleTranslate now because my English language is not good enough.

to file "settings.json" remove-empty-lines.allowedNumberOfEmptyLines=2; I defined the setting. But it still deletes all spaces. I want it to accept at least 2 spaces.

**Comment by usernamehw** [comment]
Cannot reproduce. 

Do you have my extension installed `usernamehw.remove-empty-lines` and not a fork like `thamaraiselvam.remove-blank-lines`?
