### ISSUE TITLE
Setting to remove empty lines On Save

### ISSUE THREAD

**Issue by xChillax** [usernamehw/vscode-remove-empty-lines#11]
This would make this app more automated, as I often use different extensions to fix up little formatting issues on save. While normally I have no issue inputting this command manually when working with hundreds of files this task can become a bit tedious.

Hopefully, this isn't hard to implement.

Thanks in advance!

**Comment by usernamehw** [comment]
That would require this extension to activate itself and listen to events. Right now it only activates when running commands.

Although, it's a 2Kb in size / 1ms activation time extension, so it should be fine.

**Comment by usernamehw** [comment]
```js
"remove-empty-lines.runOnSave": true,
```
