### ISSUE TITLE
Option to remove empty lines only in specific languages

### ISSUE THREAD

**Issue by tobiaswild** [usernamehw/vscode-remove-empty-lines#12]
I don't like having blank lines in my HTML documents, and for this the extension is perfect. But when it comes to CSS, I really like to have a line between each "element", but I can't set the format to save the rule on a language basis. 
Would be a great improvement for the extension.

**Comment by usernamehw** [comment]
From the next version:

```js
"[css]": {
  "remove-empty-lines.allowedNumberOfEmptyLines": 1,
},
```

**Comment by tobiaswild** [comment]
Thanks a lot!
