### ISSUE TITLE
Doesn't work with autosave

### ISSUE THREAD

**Issue by eujoaoalves** [usernamehw/vscode-remove-empty-lines#13]
How can i use this extension with autosave without using CTRL + s?

**Comment by usernamehw** [comment]
You can't ATM. It's likely not what users would expect. 

Which one do you want: `afterDelay` or `onFocusChange`?

**Comment by eujoaoalves** [comment]
i would like to use when `onFocusChange`

**Comment by usernamehw** [comment]
New configuration option (from the next version of extension):

```js
"remove-empty-lines.onSaveReason": {
	"manual": true,
	"afterDelay": false,
	"focusOut": false,
},
```
