### ISSUE TITLE
when i save my code the view usually jump down 1 line

### ISSUE THREAD

**Issue by Eden-tran** [usernamehw/vscode-remove-empty-lines#15]
Hi 
I really love your extension it help me alot while coding. But i have this question. Everytime i save it some time it will jump down the view with 1 line (although don't have any empty line need to clear). I think this is just a small problem. But if you have any solution for this please let me know. 
Thank You

**Comment by usernamehw** [comment]
Which settings do you have that are not default - In Settings UI: `@ext:usernamehw.remove-empty-lines @modified`?

**Comment by Eden-tran** [comment]
![image](https://user-images.githubusercontent.com/58251640/232320711-dda3e93f-ee67-4d2b-9ba3-74247d2b4c25.png)
which one need to set default ??

**Comment by usernamehw** [comment]
It all looks fine. I don't know why this is happening. Maybe another extension does something on save?

**Comment by Eden-tran** [comment]
{
  "[php]": {
    "editor.defaultFormatter": "bmewburn.vscode-intelephense-client"
  },
  "[php]": {
    "editor.formatOnSave": true
  },
  "workbench.iconTheme": "material-icon-theme",
  "breadcrumbs.enabled": true,
  "todohighlight.keywords": [],
  "todohighlight.isEnable": false,
  "explorer.confirmDragAndDrop": false,
  // For which languages indent-rainbow should be activated (if empty it means all).
  "indentRainbow.includedLanguages": [], // for example ["nim", "nims", "python"]
  // For which languages indent-rainbow should be deactivated (if empty it means none).
  "indentRainbow.excludedLanguages": ["plaintext", ".cpp"],
  // The delay in ms until the editor gets updated.
  "indentRainbow.updateDelay": 100, // 10 makes it super fast but may cost more resources
  // Defining custom colors instead of default "Rainbow" for dark backgrounds.
  // (Sorry: Changing them needs an editor restart for now!)
  "indentRainbow.colors": [
    "rgba(255,255,64,0.07)",
    "rgba(127,255,127,0.07)",
    "rgba(255,127,255,0.07)",
    "rgba(79,236,236,0.07)"
  ],
  // The indent color if the number of spaces is not a multiple of "tabSize".
  "indentRainbow.errorColor": "rgba(128,32,32,0.6)",
  // The indent color when there is a mix between spaces and tabs.
  // To be disabled this coloring set this to an empty string.
  "indentRainbow.tabmixColor": "rgba(128,32,96,0.6)",
  // Example of regular expression in JSON (note double backslash to escape characters)
  "indentRainbow.ignoreLinePatterns": [
    "/[ \t]* [*]/g", // lines begining with <whitespace><space>*
    "/[ \t]+[/]{2}/g" // lines begininning with <whitespace>//
  ],
  "indentRainbow.ignoreErrorLanguages": ["markdown", "haskell"],
  "explorer.confirmDelete": false,
  "php.validate.executablePath": "",
  //// html format
  "editor.insertSpaces": true,
  "editor.tabSize": 4,
  "html.format.contentUnformatted": "pre,code,textarea",
  "html.format.endWithNewline": false,
  "html.format.extraLiners": "head, body, /html",
  "html.format.indentHandlebars": false,
  "html.format.indentInnerHtml": false,
  "html.format.maxPreserveNewLines": null,
  "html.format.preserveNewLines": true,
  "html.format.wrapLineLength": 120,
  "html.format.wrapAttributes": "auto",
  "sync.gist": "86938f6dc2699e6393e02ab23ecc840d",
  "sync.removeExtensions": true,
  "workbench.startupEditor": "newUntitledFile",
  "workbench.colorTheme": "Pitch Black",
  "emmet.triggerExpansionOnTab": true, // enable tab to expanse emmet tags
  "blade.format.enable": true, // if you would like to enable blade format
  "[blade]": {
    "editor.autoClosingBrackets": "always",
    "editor.defaultFormatter": "shufo.vscode-blade-formatter"
  },
  "code-runner.executorMapByFileExtension": {
    ".vb": "cd $dir && vbc /nologo $fileName && $dir$fileNameWithoutExt",
    ".vbs": "cscript //Nologo",
    ".scala": "scala",
    ".jl": "julia",
    ".cr": "crystal",
    ".ml": "ocaml",
    ".exs": "elixir",
    ".hx": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
    ".rkt": "racket",
    ".scm": "csi -script",
    ".ahk": "autohotkey",
    ".au3": "autoit3",
    ".kt": "cd $dir && kotlinc $fileName -include-runtime -d $fileNameWithoutExt.jar && java -jar $fileNameWithoutExt.jar",
    ".kts": "kotlinc -script",
    ".dart": "dart",
    ".pas": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
    ".pp": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
    ".d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
    ".hs": "runhaskell",
    ".nim": "nim compile --verbosity:0 --hints:off --run",
    ".csproj": "dotnet run --project",
    ".fsproj": "dotnet run --project",
    ".lisp": "sbcl --script",
    ".kit": "kitc --run",
    ".v": "v run",
    ".vsh": "v run",
    ".sass": "sass --style expanded",
    ".cu": "cd $dir && nvcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
  },
  "code-runner.executorMap": {
    "javascript": "node",
    "java": "cd $dir && javac $fileName && java $fileNameWithoutExt",
    "c": "cd $dir && gcc $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    // "cpp": "cd $dir && g++ $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "cpp": "cd $dir && g++ -std=c++17 $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "objective-c": "cd $dir && gcc -framework Cocoa $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "php": "php",
    "python": "python -u",
    "perl": "perl",
    "perl6": "perl6",
    "ruby": "ruby",
    "go": "go run",
    "lua": "lua",
    "groovy": "groovy",
    "powershell": "powershell -ExecutionPolicy ByPass -File",
    "bat": "cmd /c",
    "shellscript": "bash",
    "fsharp": "fsi",
    "csharp": "scriptcs",
    "vbscript": "cscript //Nologo",
    "typescript": "ts-node",
    "coffeescript": "coffee",
    "scala": "scala",
    "swift": "swift",
    "julia": "julia",
    "crystal": "crystal",
    "ocaml": "ocaml",
    "r": "Rscript",
    "applescript": "osascript",
    "clojure": "lein exec",
    "haxe": "haxe --cwd $dirWithoutTrailingSlash --run $fileNameWithoutExt",
    "rust": "cd $dir && rustc $fileName && $dir$fileNameWithoutExt",
    "racket": "racket",
    "scheme": "csi -script",
    "ahk": "autohotkey",
    "autoit": "autoit3",
    "dart": "dart",
    "pascal": "cd $dir && fpc $fileName && $dir$fileNameWithoutExt",
    "d": "cd $dir && dmd $fileName && $dir$fileNameWithoutExt",
    "haskell": "runhaskell",
    "nim": "nim compile --verbosity:0 --hints:off --run",
    "lisp": "sbcl --script",
    "kit": "kitc --run",
    "v": "v run",
    "sass": "sass --style expanded",
    "scss": "scss --style expanded",
    "less": "cd $dir && lessc $fileName $fileNameWithoutExt.css",
   "FortranFreeForm": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran-modern": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran_fixed-form": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt",
    "fortran": "cd $dir && gfortran $fileName -o $fileNameWithoutExt && $dir$fileNameWithoutExt"
  },
  // "bracketPairColorizer.excludedLanguages": [],
  "C_Cpp.commentContinuationPatterns": ["/**"],
  "C_Cpp.default.cppStandard": "c++11",
  "C_Cpp.default.includePath": [],
  "[cpp]": {
    "editor.defaultFormatter": "ms-vscode.cpptools"
  },
  "C_Cpp.updateChannel": "Insiders",
  "editor.formatOnSave": true,
  "[html]": {
    "editor.defaultFormatter": "vscode.html-language-features"
  },
  "security.workspace.trust.untrustedFiles": "open",
  "code-runner.runInTerminal": true,
  // "bracketPairColorizer.depreciation-notice": false,
  "settingsSync.ignoredExtensions": [
    "shan.code-settings-sync",
    "coenraads.bracket-pair-colorizer-2"
  ],
  "auto-rename-tag.activationOnLanguage": ["*"],
  "editor.bracketPairColorization.enabled": true,
  "editor.guides.bracketPairs": "active",
  "bracket-pair-colorizer-2.depreciation-notice": false,
  "editor.lineHeight": 35,
  "editor.letterSpacing": 0.5,
  "liveServer.settings.donotShowInfoMsg": true,
  "liveServer.settings.donotVerifyTags": true,
  "editor.fontSize": 14,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "tabnine.experimentalAutoImports": true,
  "diffEditor.ignoreTrimWhitespace": false,
  "git.enableSmartCommit": true,
  "workbench.sideBar.location": "right",
  "php.suggest.basic": false,
  "php.validate.enable": false,
  "emmet.excludeLanguages": [
    "markdown",
    "php"
  ],
  "editor.wordWrap": "on",
  "phpsab.allowedAutoRulesets": [
    ".phpcs.xml",
    ".phpcs.xml.dist",
    "phpcs.xml",
    "phpcs.xml.dist",
    "phpcs.ruleset.xml",
    "ruleset.xml"
  ],
  "phpsab.executablePathCBF": "/Users/Eden/.composer/vendor/bin/phpcbf",
  "phpsab.executablePathCS": "/Users/Eden/.composer/vendor/bin/phpcs",
  "terminal.integrated.enableMultiLinePasteWarning": false,
  // "editor.codeActionsOnSave": {
  // },
  "trailing-spaces.syntaxIgnore": [
    { "trailing-spaces.trimOnSave": true }
  ],
  "tabnine.disableFileRegex": [],
  "remove-empty-lines.runOnSave": true,
  "remove-empty-lines.allowedNumberOfEmptyLines": 0,
  // "trailing-spaces.trimOnSave": true,
  "editor.trimAutoWhitespace": false,
  "trailing-spaces.includeEmptyLines": false
}


This is all my setting.json you can check. Sorry if it look messy :(

**Comment by Eden-tran** [comment]
oh i may know the problem. The confilct is make by the Php intelephense. When i disable the PHP intelephense everything work fine

**Comment by usernamehw** [comment]
Closing as the problem was with another extension.
