### ISSUE TITLE
Doesn't seem to worK

### ISSUE THREAD

**Issue by ognik777** [usernamehw/vscode-remove-empty-lines#2]
have a php file, lots of empty lines.
Installed the extension, tried ctrl + shift + 9, no change.  Closed VSC, tried agin, nothing.  What am I missing please?

**Comment by usernamehw** [comment]
@ognik777  Extension doesn't define any keyboard shortcuts by default. 

I guess the description should be updated.

**Comment by usernamehw** [comment]
You can see everything extension adds in `Contributions` part of the Extension:

![screenshot 80](https://user-images.githubusercontent.com/9638156/53705757-c1611800-3e37-11e9-8e5b-54602aa61190.png)

**Comment by usernamehw** [comment]
I have updated extension description with warning:

# ⚠⚠⚠ Extension doesn't define any keyboard shortcuts

And a link to stackoverflow how to open `keybindings.json`.

**Comment by ognik777** [comment]
Cool, thanks.  Bit of a newby, me J  Great extension
