### ISSUE TITLE
It's not working for me.

### ISSUE THREAD

**Issue by nirmalsinghoo7** [usernamehw/vscode-remove-empty-lines#6]
I have installed the addon and configured. When I tried to run the command in .CSS file by selecting the whole document, It not removing the empty lines. 
I press F1 > Remove empty lines in Document. - https://prnt.sc/v4i8vx
Nothing happened. I tried shortcut too but not working.

**Comment by usernamehw** [comment]
Could you try to use my extension in Insiders vscode version?

https://code.visualstudio.com/insiders/

**Comment by nirmalsinghoo7** [comment]
Yes, It's working fine in Insiders VSCode. It works with both conditions In document and In selection.

**Comment by usernamehw** [comment]
This extension has 1 setting `remove-empty-lines.allowedNumberOfEmptyLines`. Is it a default value (0)?

**Comment by nirmalsinghoo7** [comment]
Yes, It's Zero - https://prnt.sc/v5up1e

**Comment by usernamehw** [comment]
That's a screenshot from `Insiders`. Is it the same in `Stable` (blue). They have separate locations for configuration/cache/extensions.

**Comment by nirmalsinghoo7** [comment]
I have not found this on the stable version. Please guide me on how to find that setting.
Thank you!

**Comment by usernamehw** [comment]
The same way as in Insiders. Just execute `Preferences: Open Settings (UI)` from the command palette from Stable (blue icon) vscode

or <kbd>Ctrl</kbd>+<kbd>,</kbd> /  <kbd>⌘</kbd>+<kbd>,</kbd>

**Comment by nirmalsinghoo7** [comment]
I have tried this method but not working. It's not found any setting - https://prnt.sc/v5uw9m

**Comment by usernamehw** [comment]
Do you have the extension installed and enabled?

Search for `usernamehw.remove-empty-lines` in Extesions View

![Screenshot (361)](https://user-images.githubusercontent.com/9638156/97079031-5f02ef80-15f9-11eb-96ab-8b3f1ae8f299.png)

**Comment by nirmalsinghoo7** [comment]
Yes, It's installed and Enabled - https://prnt.sc/v5vdqr

**Comment by usernamehw** [comment]
My best guess is either one of the installed extensions is crashing or something is wrong with installation of vscode.

You can try to run those commands:

1. `Developer: Show Running Extensions`

Will show running extensions sorted by activation time (and, possibly, exceptions)

2. `Developer: Toggle Developer Tools`

Will show thrown exceptions.

**Comment by nirmalsinghoo7** [comment]
I have installed this `Developer: Show Running Extensions` It has updated some plugins.
But issue is still there.

**Comment by usernamehw** [comment]
`Developer: Show Running Extensions` and `Developer: Toggle Developer Tools` are commands. You run them to see if an extension takes too long to run or has exceptions.

**Comment by nirmalsinghoo7** [comment]
I have run these commands. 
`Developer: Show Running Extensions` - https://prnt.sc/v6rh5c
`Developer: Toggle Developer Tools` - Nothing happens on this command - https://prnt.sc/v6rhkw

Please suggest to me, what is next?
My VS Code has latest version.

**Comment by usernamehw** [comment]
No no, you run them from `Command Palette` <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>

**Comment by nirmalsinghoo7** [comment]
`Developer: Toggle Developer Tools` - https://prnt.sc/v6xu5u

**Comment by nirmalsinghoo7** [comment]
Hello @usernamehw 
Still I have not found any solution for this. I have to open VS Code Insider to remove empty lines from the code.
Do you have still any solution for this? else I will disable and remove this add-on.

Regards,
Nirmal Singh

**Comment by usernamehw** [comment]
@nirmalsinghoo7 I cannot reproduce this issue.

Done some refactoring just now: https://github.com/usernamehw/vscode-remove-empty-lines/commit/7833758b8452508b7c2127ba06b45730bd325abf . VSCode version required **1.56** for the new version of extension. Maybe it will change something or maybe not.

**Comment by usernamehw** [comment]
If it's still not working you can try other extensions that look similar:

- https://marketplace.visualstudio.com/items?itemName=ylw1694.removeEmptyLines
- https://marketplace.visualstudio.com/items?itemName=Thamaraiselvam.remove-blank-lines
- https://marketplace.visualstudio.com/items?itemName=rintoj.blank-line-organizer
- https://marketplace.visualstudio.com/items?itemName=ctf0.blank-line-organizer
