### ISSUE TITLE
[Feature Request] Add settings for minimum consecutive empty-line to be left out

### ISSUE THREAD

**Issue by Cyberavater** [usernamehw/vscode-remove-empty-lines#8]
Suppose I have 5 consecutive empty lines in my code, now when I use this extension I expect it to remove empty lines till there are only 2 consecutive empty lines in my code. [Note this 5 (or more) consecutive empty lines can occur multiple times on this page, every time I'd want it as 2 (n) consecutive empty lines in my code.]

**Comment by usernamehw** [comment]
How would it be different from `"remove-empty-lines.allowedNumberOfEmptyLines": 2,`? Pls, add example.

**Comment by Cyberavater** [comment]
Yes, this is exactly what I wanted! I didn't know this existed. Thanks for this extension.
