### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by ghost** [usernamehw/vscode-remove-empty-lines#9]
After updating to version 0.0.7 I could not remove empty lines in document on Windows 1o, showing me the error
`Command 'Remove empty lines: in Document' resulted in an error (command 'remove-empty-lines.inDocument' not found)`

![image](https://user-images.githubusercontent.com/84993137/126378430-e1c22893-dc5f-4118-b505-8ab8b75db130.png)

**Comment by usernamehw** [comment]
Does it work with `0.0.8`?

**Comment by RicaBenhossi** [comment]
WOW!!!!! That was fast...

Worked like magic... perfect.

Thank you so much ;)

**Comment by usernamehw** [comment]
Ok. Closing then.
